# Generated by Django 4.0 on 2021-12-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='author',
            new_name='maker',
        ),
    ]
